### PR TITLE
added touch-events to selection

### PR DESCRIPTION
**Pull request by AlexandreKilian**

### CODE REVIEW

**Comment by abhiaiyer91** [comment]
+1 for this fix

**Comment by mattschoch** [comment]
+1

**Comment by kenny-hibino** [comment]
Thank you for this PR @AlexandreKilian ! 
Before we merge this branch, would you mind re-writing the commit message? This project uses `commitizen` to format the commit message and use the message for versioning the library. Please see the [CONTRIBUTING.md](https://github.com/kenny-hibino/react-places-autocomplete/blob/master/CONTRIBUTING.md)!

```sh
git reset --soft HEAD^ # Undo the last commit
npm run commit # Please pick `fix` for this PR :)
```

Let me know if you have any questions :)

**Comment by AlexandreKilian** [comment]
@kenny-hibino done

**Comment by kenny-hibino** [comment]
Thank you @AlexandreKilian for this fix!

**Pull request merged**
