### PR TITLE
Add googleLogoSrc prop

### LINKED ISSUE #119: Using with next.js
I'm not really sure where to report this issue, but basically, the inclusion of Google image imports makes this very difficult to use with next.js (SSR).

When I follow the instructions, I end up getting

```
Uncaught Error: Module parse failed: node_modules\react-places-autocomplete\dist\images\powered_by_google_default.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

Would you happen to know anything about how to resolve this? All of the existing answers that I've seen involve handling images on project code, not external components.

(I personally think that the images shouldn't really be shipped in the library and should be passed in as a prop or included as inline SVGs instead for retina support, but that's another issue.)

### PR DESCRIPTION
**Pull request by JonAbrams**
Fixes #119

Allows the dev to specify a url or path to their own provided "Powered by Google" logo.

### CODE REVIEW

**Comment by davidcoleman007** [comment]
+1

**Comment by JonAbrams** [comment]
Looks like the new `renderFooter` prop removes the need for this PR.

**Comment by tanguyantoine** [comment]
I still have the issue even if I use `renderFooter={() =>null}`

**Comment by kenny-hibino** [comment]
@tanguyantoine Please make sure to install `v6.0.0-beta.1` to use `renderFooter` prop 👍

**Comment by tanguyantoine** [comment]
That did he tricks, thank you. btw, very good job 👍

**Pull request closed without merging**
