### PR TITLE
Add demo app

### PR DESCRIPTION
**Pull request by cburbank**
Hi @kenny-hibino, 

I've enjoyed using your library, and I saw that you mentioned possibly setting up a demo for it. I took a shot at creating a small demo app that implements both the PlacesAutocomplete component and the geocoding functionality. I added a couple of demo-related scripts to package.json: 'demo' runs the demo locally with webpack-dev-server, 'demo:test' runs the demo's tests, and 'demo:build' builds the app for production.

The demo app is deployed live [here](http://mindless-bean.surge.sh/) if you want to take a look. I didn't add this link to the readme but you're welcome to use it if you'd like.

Thanks!

### CODE REVIEW

**Comment by kenny-hibino** [comment]
@cburbank This PR is fantastic! Do you mind having this demo as the project [Github Page](https://pages.github.com/)? I had a hard time finding time to work on this, but I'm SO glad that you did this 👍

**Comment by cburbank** [comment]
@kenny-hibino No problem at all, feel free to use it however you'd like!

**Comment by kenny-hibino** [comment]
Hi @cburbank! I'm having a difficult time publishing the demo site under this project 
Github page[URL](https://kenny-hibino.github.io/react-places-autocomplete/)

Do you know how to go about publishing the page? It looks like ES6 is not transpired into ES5 and getting an error in the console.

**Comment by cburbank** [comment]
Hey @kenny-hibino ,

It looks like you have to publish the transpiled code directly to the gh-pages branch. I was able to get it working by using [gh-pages](https://www.npmjs.com/package/gh-pages) and adding a "demo:deploy" script that automatically publishes the contents of demo/dist to the remote gh-pages branch. So to deploy the demo, you would run:

1. npm run demo:build
2. npm run demo:deploy

I left them as two separate commands but they could definitely be combined into one.

You can see it working on my fork's [gh-pages site](https://cburbank.github.io/react-places-autocomplete/).

You'll need to add your API key to index.html prior to publishing. I didn't include my key with the commit because I wasn't sure how you wanted to handle that. You could either leave your key out and add it manually every time you deploy, or commit it and add a domain restriction so it only works with specific domains.

I also had to go to the Google API dashboard and enable the geocoding API because I was getting errors when it tried to call the geocoding service. I hadn't realized it's separate from the Google Places API.

I'll open a pull request that has these changes.

Thanks!

**Comment by kenny-hibino** [comment]
@cburbank That's great! Thank you so much for this, I'll check out the PR and publish the demo on the Github Pages.

**Pull request merged**
