### PR TITLE
Feature/include original value in autocomplete

### PR DESCRIPTION
**Pull request by markph1990**
This PR is related to issue #141.

### CODE REVIEW

**Comment by kenny-hibino** [comment]
@markph1990 Thank you for this PR. I gave some thought about this and I think we don't need to add a prop to configure the behavior. Instead, we can make this a default behavior 👍

**Comment by markph1990** [comment]
Ok then, I'll remove documentation part (since it will be redundant) and fix implementation and test parts so that this is a default feature.

**Comment by markph1990** [comment]
I've made this a default behaviour. I think tests can stay as they are (I only tweaked description for them).

**Comment by kenny-hibino** [comment]
Thanks @markph1990 !! I will take a look at this PR within the next few days 👍

**Pull request merged**
